terraform {
  required_version = "~> 1.11"

  required_providers {
    azapi = {
      source  = "Azure/azapi"
      version = "~> 2.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }

  # Partial backend. Values come from a per-student file generated by
  # bootstrap/backend.sh|ps1 — never committed.
  #
  #   cd infra
  #   terraform init -backend-config=../bootstrap/backend.tfbackend
  backend "azurerm" {}
}

provider "azapi" {
  # azapi picks up credentials from `az login` (local) or OIDC (CI).
  # No provider configuration needed for the course.
}

provider "azurerm" {
  features {}
  # azurerm is declared so the per-module bilingual callouts can show the
  # equivalent azurerm_* resource. No azurerm_* resource is used in main.tf.
}
